### ISSUE TITLE
Create project

### ISSUE THREAD

**Issue by Kirillfn** [oleksandrblazhko/ai-214-lukachinskij#6]

**Comment by oleksandrblazhko** [comment]
Для вас створено проект з назвою, яка співпадає з назвою вашого репозиторію.
Подальші кроки наведено в підрозділі "2.5 Налаштування GitHub-проекту" - 
https://drive.google.com/file/d/171urKXJfONJ21G4F8VjFmuqZjXVGea-9/view

**Comment by Kirillfn** [comment]
Виконав

пт, 13 окт. 2023 г. в 19:43, Oleksandr Blazhko ***@***.***>:
